#!/bin/ash /etc/rc.common

START=99

start() {
	sleep 5   # make sure boot process is done, no more console msgs
	echo "WiFi_Printer"
	node /root/wifi_printer/app.js
}

stop() {
	kill -9 `ps | grep "node /root/wifi_printer/app.js" | awk '{if(NR==1)print$1}'`
}
